//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(DeudaMetaData))]

    public partial class Deuda
    {
        public int Id { get; set; }
        public int IdAsignacion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int Estado { get; set; }
        public Dictionary<int, string> Estados
        {
            get
            {
                return new Dictionary<int, string> { { 0, "Not payed" }, { 1, "Payed" } };
            }
            set { }
        }

        public virtual AsignacionPlan AsignacionPlan { get; set; }
    }
}
