//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidentes
    {
        public int Id { get; set; }
        public int IdResidencia { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
    
        public virtual Residencia Residencia { get; set; }
    }
}
