//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InformacionMetaData))]
    public partial class Informacion
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public int Tipo { get; set; }
        public Dictionary<int, string> Tipos
        {
            get
            {
                return new Dictionary<int, string> { { 1, "Notices" }, { 2, "News" }, { 3, "Rules" }, { 4, "Proceedings " }, { 5, "Financial State" }, { 6, "Security Updates" } };
            }
            set { }
        }
    }
}
