//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCobroRubro
    {
        public int IdPlan { get; set; }
        public int IdRubro { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
    }
}
